"""Seed data for PrithviTwin backend (auto-synced from lib/seedData.ts)."""

KARNATAKA_DISTRICTS = [
    {
        "name": "Bengaluru Urban",
        "baselineRainfall": 85,
        "baselineTemp": 28.5,
        "rainfallStdDev": 30,
        "tempStdDev": 1.5,
        "floodRiskBase": 0.15,
        "droughtRiskBase": 0.2,
        "activeMonsoonDays": 12,
        "breakMonsoonDays": 8,
        "predictionConfidence": 0.88,
    },
    {
        "name": "Bengaluru Rural",
        "baselineRainfall": 78,
        "baselineTemp": 27.8,
        "rainfallStdDev": 28,
        "tempStdDev": 1.4,
        "floodRiskBase": 0.1,
        "droughtRiskBase": 0.25,
        "activeMonsoonDays": 11,
        "breakMonsoonDays": 9,
        "predictionConfidence": 0.85,
    },
    {
        "name": "Mysuru",
        "baselineRainfall": 72,
        "baselineTemp": 27.2,
        "rainfallStdDev": 25,
        "tempStdDev": 1.3,
        "floodRiskBase": 0.12,
        "droughtRiskBase": 0.28,
        "activeMonsoonDays": 10,
        "breakMonsoonDays": 10,
        "predictionConfidence": 0.82,
    },
    {
        "name": "Dharwad",
        "baselineRainfall": 92,
        "baselineTemp": 29.1,
        "rainfallStdDev": 32,
        "tempStdDev": 1.6,
        "floodRiskBase": 0.2,
        "droughtRiskBase": 0.18,
        "activeMonsoonDays": 14,
        "breakMonsoonDays": 7,
        "predictionConfidence": 0.8,
    },
    {
        "name": "Belagavi",
        "baselineRainfall": 105,
        "baselineTemp": 28.0,
        "rainfallStdDev": 38,
        "tempStdDev": 1.5,
        "floodRiskBase": 0.35,
        "droughtRiskBase": 0.12,
        "activeMonsoonDays": 16,
        "breakMonsoonDays": 6,
        "predictionConfidence": 0.78,
    },
    {
        "name": "Kalaburagi",
        "baselineRainfall": 52,
        "baselineTemp": 31.5,
        "rainfallStdDev": 22,
        "tempStdDev": 2.0,
        "floodRiskBase": 0.08,
        "droughtRiskBase": 0.55,
        "activeMonsoonDays": 8,
        "breakMonsoonDays": 14,
        "predictionConfidence": 0.76,
    },
    {
        "name": "Ballari",
        "baselineRainfall": 48,
        "baselineTemp": 32.2,
        "rainfallStdDev": 20,
        "tempStdDev": 2.1,
        "floodRiskBase": 0.05,
        "droughtRiskBase": 0.6,
        "activeMonsoonDays": 7,
        "breakMonsoonDays": 15,
        "predictionConfidence": 0.75,
    },
    {
        "name": "Raichur",
        "baselineRainfall": 46,
        "baselineTemp": 33.0,
        "rainfallStdDev": 20,
        "tempStdDev": 2.2,
        "floodRiskBase": 0.06,
        "droughtRiskBase": 0.65,
        "activeMonsoonDays": 7,
        "breakMonsoonDays": 16,
        "predictionConfidence": 0.74,
    },
    {
        "name": "Bidar",
        "baselineRainfall": 60,
        "baselineTemp": 30.5,
        "rainfallStdDev": 24,
        "tempStdDev": 1.8,
        "floodRiskBase": 0.1,
        "droughtRiskBase": 0.42,
        "activeMonsoonDays": 9,
        "breakMonsoonDays": 12,
        "predictionConfidence": 0.77,
    },
    {
        "name": "Vijayapura",
        "baselineRainfall": 50,
        "baselineTemp": 31.8,
        "rainfallStdDev": 22,
        "tempStdDev": 2.0,
        "floodRiskBase": 0.07,
        "droughtRiskBase": 0.58,
        "activeMonsoonDays": 8,
        "breakMonsoonDays": 14,
        "predictionConfidence": 0.75,
    },
    {
        "name": "Bagalkot",
        "baselineRainfall": 58,
        "baselineTemp": 30.8,
        "rainfallStdDev": 23,
        "tempStdDev": 1.9,
        "floodRiskBase": 0.12,
        "droughtRiskBase": 0.45,
        "activeMonsoonDays": 9,
        "breakMonsoonDays": 13,
        "predictionConfidence": 0.76,
    },
    {
        "name": "Gadag",
        "baselineRainfall": 65,
        "baselineTemp": 30.0,
        "rainfallStdDev": 26,
        "tempStdDev": 1.7,
        "floodRiskBase": 0.15,
        "droughtRiskBase": 0.38,
        "activeMonsoonDays": 10,
        "breakMonsoonDays": 11,
        "predictionConfidence": 0.78,
    },
    {
        "name": "Haveri",
        "baselineRainfall": 80,
        "baselineTemp": 29.5,
        "rainfallStdDev": 30,
        "tempStdDev": 1.6,
        "floodRiskBase": 0.18,
        "droughtRiskBase": 0.25,
        "activeMonsoonDays": 12,
        "breakMonsoonDays": 9,
        "predictionConfidence": 0.8,
    },
    {
        "name": "Uttara Kannada",
        "baselineRainfall": 280,
        "baselineTemp": 26.0,
        "rainfallStdDev": 80,
        "tempStdDev": 1.2,
        "floodRiskBase": 0.55,
        "droughtRiskBase": 0.05,
        "activeMonsoonDays": 20,
        "breakMonsoonDays": 4,
        "predictionConfidence": 0.72,
    },
    {
        "name": "Dakshina Kannada",
        "baselineRainfall": 320,
        "baselineTemp": 27.5,
        "rainfallStdDev": 90,
        "tempStdDev": 1.1,
        "floodRiskBase": 0.6,
        "droughtRiskBase": 0.03,
        "activeMonsoonDays": 22,
        "breakMonsoonDays": 3,
        "predictionConfidence": 0.7,
    },
    {
        "name": "Udupi",
        "baselineRainfall": 300,
        "baselineTemp": 27.0,
        "rainfallStdDev": 85,
        "tempStdDev": 1.1,
        "floodRiskBase": 0.58,
        "droughtRiskBase": 0.04,
        "activeMonsoonDays": 21,
        "breakMonsoonDays": 3,
        "predictionConfidence": 0.71,
    },
    {
        "name": "Shivamogga",
        "baselineRainfall": 180,
        "baselineTemp": 27.8,
        "rainfallStdDev": 55,
        "tempStdDev": 1.3,
        "floodRiskBase": 0.4,
        "droughtRiskBase": 0.08,
        "activeMonsoonDays": 17,
        "breakMonsoonDays": 5,
        "predictionConfidence": 0.75,
    },
    {
        "name": "Chikkamagaluru",
        "baselineRainfall": 160,
        "baselineTemp": 26.5,
        "rainfallStdDev": 50,
        "tempStdDev": 1.2,
        "floodRiskBase": 0.38,
        "droughtRiskBase": 0.1,
        "activeMonsoonDays": 16,
        "breakMonsoonDays": 5,
        "predictionConfidence": 0.76,
    },
    {
        "name": "Hassan",
        "baselineRainfall": 110,
        "baselineTemp": 27.0,
        "rainfallStdDev": 38,
        "tempStdDev": 1.3,
        "floodRiskBase": 0.25,
        "droughtRiskBase": 0.15,
        "activeMonsoonDays": 14,
        "breakMonsoonDays": 7,
        "predictionConfidence": 0.78,
    },
    {
        "name": "Kodagu",
        "baselineRainfall": 380,
        "baselineTemp": 22.0,
        "rainfallStdDev": 100,
        "tempStdDev": 1.0,
        "floodRiskBase": 0.72,
        "droughtRiskBase": 0.02,
        "activeMonsoonDays": 24,
        "breakMonsoonDays": 2,
        "predictionConfidence": 0.68,
    },
    {
        "name": "Mandya",
        "baselineRainfall": 68,
        "baselineTemp": 28.5,
        "rainfallStdDev": 26,
        "tempStdDev": 1.4,
        "floodRiskBase": 0.14,
        "droughtRiskBase": 0.32,
        "activeMonsoonDays": 10,
        "breakMonsoonDays": 11,
        "predictionConfidence": 0.8,
    },
    {
        "name": "Chamarajanagara",
        "baselineRainfall": 62,
        "baselineTemp": 29.0,
        "rainfallStdDev": 24,
        "tempStdDev": 1.5,
        "floodRiskBase": 0.1,
        "droughtRiskBase": 0.4,
        "activeMonsoonDays": 9,
        "breakMonsoonDays": 12,
        "predictionConfidence": 0.79,
    },
    {
        "name": "Tumakuru",
        "baselineRainfall": 70,
        "baselineTemp": 28.8,
        "rainfallStdDev": 27,
        "tempStdDev": 1.4,
        "floodRiskBase": 0.12,
        "droughtRiskBase": 0.3,
        "activeMonsoonDays": 10,
        "breakMonsoonDays": 10,
        "predictionConfidence": 0.81,
    },
    {
        "name": "Chikkaballapura",
        "baselineRainfall": 65,
        "baselineTemp": 28.5,
        "rainfallStdDev": 25,
        "tempStdDev": 1.4,
        "floodRiskBase": 0.11,
        "droughtRiskBase": 0.33,
        "activeMonsoonDays": 10,
        "breakMonsoonDays": 10,
        "predictionConfidence": 0.8,
    },
    {
        "name": "Kolar",
        "baselineRainfall": 60,
        "baselineTemp": 29.5,
        "rainfallStdDev": 24,
        "tempStdDev": 1.5,
        "floodRiskBase": 0.09,
        "droughtRiskBase": 0.38,
        "activeMonsoonDays": 9,
        "breakMonsoonDays": 12,
        "predictionConfidence": 0.79,
    },
    {
        "name": "Ramanagara",
        "baselineRainfall": 72,
        "baselineTemp": 28.0,
        "rainfallStdDev": 27,
        "tempStdDev": 1.3,
        "floodRiskBase": 0.13,
        "droughtRiskBase": 0.28,
        "activeMonsoonDays": 11,
        "breakMonsoonDays": 9,
        "predictionConfidence": 0.82,
    },
    {
        "name": "Koppal",
        "baselineRainfall": 50,
        "baselineTemp": 32.0,
        "rainfallStdDev": 21,
        "tempStdDev": 2.0,
        "floodRiskBase": 0.07,
        "droughtRiskBase": 0.58,
        "activeMonsoonDays": 7,
        "breakMonsoonDays": 15,
        "predictionConfidence": 0.74,
    },
    {
        "name": "Yadgir",
        "baselineRainfall": 44,
        "baselineTemp": 33.5,
        "rainfallStdDev": 19,
        "tempStdDev": 2.2,
        "floodRiskBase": 0.06,
        "droughtRiskBase": 0.68,
        "activeMonsoonDays": 6,
        "breakMonsoonDays": 17,
        "predictionConfidence": 0.72,
    },
    {
        "name": "Davanagere",
        "baselineRainfall": 75,
        "baselineTemp": 29.8,
        "rainfallStdDev": 28,
        "tempStdDev": 1.6,
        "floodRiskBase": 0.16,
        "droughtRiskBase": 0.28,
        "activeMonsoonDays": 11,
        "breakMonsoonDays": 10,
        "predictionConfidence": 0.8,
    },
    {
        "name": "Chitradurga",
        "baselineRainfall": 55,
        "baselineTemp": 30.5,
        "rainfallStdDev": 22,
        "tempStdDev": 1.8,
        "floodRiskBase": 0.09,
        "droughtRiskBase": 0.48,
        "activeMonsoonDays": 8,
        "breakMonsoonDays": 13,
        "predictionConfidence": 0.77,
    },
]

INDIA_STATE_SUMMARIES = [
    {
        "name": "Andhra Pradesh",
        "code": "AP",
        "stabilityScore": 62,
        "rainfall": 88,
        "temp": 30.2,
        "primaryRisk": "Cyclone risk",
    },
    {
        "name": "Arunachal Pradesh",
        "code": "AR",
        "stabilityScore": 78,
        "rainfall": 280,
        "temp": 18.5,
        "primaryRisk": "Landslide",
    },
    {
        "name": "Assam",
        "code": "AS",
        "stabilityScore": 55,
        "rainfall": 220,
        "temp": 26.0,
        "primaryRisk": "Flood",
    },
    {
        "name": "Bihar",
        "code": "BR",
        "stabilityScore": 49,
        "rainfall": 92,
        "temp": 29.5,
        "primaryRisk": "Flood/Drought",
    },
    {
        "name": "Chhattisgarh",
        "code": "CG",
        "stabilityScore": 67,
        "rainfall": 115,
        "temp": 28.8,
        "primaryRisk": "Moderate",
    },
    {
        "name": "Goa",
        "code": "GA",
        "stabilityScore": 74,
        "rainfall": 310,
        "temp": 27.0,
        "primaryRisk": "Flood risk",
    },
    {
        "name": "Gujarat",
        "code": "GJ",
        "stabilityScore": 58,
        "rainfall": 55,
        "temp": 32.0,
        "primaryRisk": "Drought",
    },
    {
        "name": "Haryana",
        "code": "HR",
        "stabilityScore": 61,
        "rainfall": 48,
        "temp": 31.5,
        "primaryRisk": "Drought",
    },
    {
        "name": "Himachal Pradesh",
        "code": "HP",
        "stabilityScore": 72,
        "rainfall": 160,
        "temp": 15.2,
        "primaryRisk": "Landslide",
    },
    {
        "name": "Jharkhand",
        "code": "JH",
        "stabilityScore": 60,
        "rainfall": 108,
        "temp": 28.0,
        "primaryRisk": "Drought",
    },
    {
        "name": "Karnataka",
        "code": "KA",
        "stabilityScore": 63,
        "rainfall": 95,
        "temp": 28.5,
        "primaryRisk": "Mixed",
    },
    {
        "name": "Kerala",
        "code": "KL",
        "stabilityScore": 71,
        "rainfall": 290,
        "temp": 27.5,
        "primaryRisk": "Flood",
    },
    {
        "name": "Madhya Pradesh",
        "code": "MP",
        "stabilityScore": 64,
        "rainfall": 82,
        "temp": 30.0,
        "primaryRisk": "Drought",
    },
    {
        "name": "Maharashtra",
        "code": "MH",
        "stabilityScore": 60,
        "rainfall": 90,
        "temp": 29.8,
        "primaryRisk": "Mixed",
    },
    {
        "name": "Manipur",
        "code": "MN",
        "stabilityScore": 69,
        "rainfall": 190,
        "temp": 21.5,
        "primaryRisk": "Landslide",
    },
    {
        "name": "Meghalaya",
        "code": "ML",
        "stabilityScore": 76,
        "rainfall": 350,
        "temp": 20.0,
        "primaryRisk": "Flood",
    },
    {
        "name": "Mizoram",
        "code": "MZ",
        "stabilityScore": 73,
        "rainfall": 240,
        "temp": 21.0,
        "primaryRisk": "Landslide",
    },
    {
        "name": "Nagaland",
        "code": "NL",
        "stabilityScore": 71,
        "rainfall": 200,
        "temp": 20.5,
        "primaryRisk": "Landslide",
    },
    {
        "name": "Odisha",
        "code": "OD",
        "stabilityScore": 52,
        "rainfall": 120,
        "temp": 30.5,
        "primaryRisk": "Cyclone/Flood",
    },
    {
        "name": "Punjab",
        "code": "PB",
        "stabilityScore": 63,
        "rainfall": 52,
        "temp": 30.0,
        "primaryRisk": "Drought",
    },
    {
        "name": "Rajasthan",
        "code": "RJ",
        "stabilityScore": 38,
        "rainfall": 28,
        "temp": 35.5,
        "primaryRisk": "Critical drought",
    },
    {
        "name": "Sikkim",
        "code": "SK",
        "stabilityScore": 68,
        "rainfall": 220,
        "temp": 12.0,
        "primaryRisk": "Glacial risk",
    },
    {
        "name": "Tamil Nadu",
        "code": "TN",
        "stabilityScore": 65,
        "rainfall": 78,
        "temp": 30.8,
        "primaryRisk": "Drought/Cyclone",
    },
    {
        "name": "Telangana",
        "code": "TS",
        "stabilityScore": 61,
        "rainfall": 72,
        "temp": 31.2,
        "primaryRisk": "Drought",
    },
    {
        "name": "Tripura",
        "code": "TR",
        "stabilityScore": 70,
        "rainfall": 185,
        "temp": 25.5,
        "primaryRisk": "Flood",
    },
    {
        "name": "Uttar Pradesh",
        "code": "UP",
        "stabilityScore": 55,
        "rainfall": 62,
        "temp": 30.5,
        "primaryRisk": "Flood/Drought",
    },
    {
        "name": "Uttarakhand",
        "code": "UK",
        "stabilityScore": 67,
        "rainfall": 175,
        "temp": 14.0,
        "primaryRisk": "Glacial/Flood",
    },
    {
        "name": "West Bengal",
        "code": "WB",
        "stabilityScore": 54,
        "rainfall": 155,
        "temp": 29.0,
        "primaryRisk": "Flood/Cyclone",
    },
    {
        "name": "Jammu and Kashmir",
        "code": "JK",
        "stabilityScore": 66,
        "rainfall": 140,
        "temp": 10.0,
        "primaryRisk": "Glacial risk",
    },
    {
        "name": "Ladakh",
        "code": "LA",
        "stabilityScore": 72,
        "rainfall": 20,
        "temp": 5.0,
        "primaryRisk": "Glacial risk",
    },
    {
        "name": "Delhi",
        "code": "DL",
        "stabilityScore": 45,
        "rainfall": 42,
        "temp": 32.5,
        "primaryRisk": "Heatwave/Drought",
    },
    {
        "name": "Puducherry",
        "code": "PY",
        "stabilityScore": 64,
        "rainfall": 82,
        "temp": 30.5,
        "primaryRisk": "Cyclone",
    },
]

KARNATAKA_INCIDENT = {
    "name": "2019 North Karnataka Floods",
    "location": "Belagavi District",
    "coordinates": [74.4977, 15.8497],
    "date": "August 2019",
    "description": "Severe flooding triggered by 3–4× above-normal rainfall during an extended Active spell, displacing over 8 lakh people across North Karnataka. The Malaprabha and Krishna river systems breached capacity.",
    "recordedRainfall": 280,
    "recordedTemp": 26.5,
    "consecutiveDryDaysBefore": 2,
    "monsoonActiveDays": 18,
    "monsoonBreakDays": 2,
    "soilMoisture": "High",
    "rainfallPctChange": 167,
    "tempOffset": -1.5,
}
